import os
import json
import argparse
import subprocess
from datetime import datetime
from argparse import Namespace
import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from systems import generate_inputs_and_folders as giaf 


def get_completed_files(log_path):
    """Return a set of base_names already recorded in the log file."""
    if not os.path.exists(log_path):
        open(log_path, "a").close()
        return set()
    with open(log_path, "r") as logf:
        return {line.strip().split(",")[1] for line in logf if line.strip()}


def log_completed_run(log_path, base_name, cmd):
    """Append a timestamped entry for a completed run."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(log_path, "a") as logf:
        logf.write(f"{timestamp},{base_name},{cmd}\n")

def main():
    parser = argparse.ArgumentParser(
        description="Run inputs generated by `generate_inputs_and_folders.py`"
    )

    parser.add_argument(
        "metadata_path",
        help="Path to metadata"
    )

    parser.add_argument(
        "-M", "--memory",
        default=45,
        required=False,
        help="Memory in GB for qmolpro job"
    )
    parser.add_argument(
        "-v", "--version",
        default='f12devel',
        required=False,
        help="Version of molpro (see qmolpro -h for more info) job"
    )

    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Print commands instead of executing them"
    )

    parser.add_argument(
            "--rerun",
            action="store_true",
            help="Rerun an input even if it was previously logged to be run"
    )
    parser.add_argument("--qmolpro-path", default="~/q-scripts/qmolpro-generic")


    args = parser.parse_args()
    meta = giaf.read_metadata(args.metadata_path)

    # Prepare args for generate_file_paths
    args_dict = {
        "metadata_path": args.metadata_path,
        "dry_run": False,
        "output": None,
    }
    args_ns = Namespace(**args_dict)

    for file_paths, folder_path, _, kwargs in giaf.generate_file_paths(args_ns, meta):
        log_path = os.path.join(folder_path, "runs.log")
        completed_files = get_completed_files(log_path)
        

        for file_path in file_paths:
            if file_path.endswith('.inp'):
                break

        base_name = os.path.basename(file_path)
        if base_name in completed_files and not args.rerun:
            print(f"✅ Skipping already completed: {file_path}")
            continue

        if "memory_in_command" in kwargs:
            memory = kwargs['memory_in_command']
        else:
            memory = args.memory

        if 'version' in kwargs:
            version = kwargs["version"]
        else:
            version = args.version

        cmd = f"{args.qmolpro_path} -M {memory} -v {version}"
        cmd += f" {base_name}"

        if args.dry_run:
            print(f"[DRY-RUN] Would run: {cmd} in {folder_path}")
            continue

        print(f"🚀 Running: {cmd} in {folder_path}")
        try:
            subprocess.run(
                cmd,
                shell=True,
                check=True,
                cwd=folder_path,
                executable="/bin/bash"
            )
        except subprocess.CalledProcessError as e:
            print(f"❌ Error running {cmd}: {e}")
            cmd += "  FAIL"

        log_completed_run(log_path, base_name, cmd)
        print(f"📝 Logged run: {base_name}")

    history_folder = os.path.dirname(os.path.realpath(__file__))
    history_path = os.path.join(
            history_folder,
            "run_history.log"
            )
    metpath_from_systems = os.path.relpath(args.metadata_path, history_folder)
    log_completed_run(history_path, metpath_from_systems, " ".join(sys.argv))

if __name__ == "__main__":
    main()
    
